#!/usr/bin/env ruby
# encoding: utf-8

class ChangeAuthor
  INFO = "Change author name and email\nUsage: git change-author [--name OLD_NAME NEW_NAME] [--email OLD_EMAIL NEW_EMAIL]"

  def initialize(args)
    puts INFO
    @type, @old, @new, *_ = args
  end

  def run
    case @type
    when '--name'
      update_name(@old, @new)
    when '--email'
      update_email(@old, @new)
    end
  end

  # update email address author and committer
  def update_email (old, new)
    `git filter-branch -f --commit-filter '
       if [ "$GIT_AUTHOR_EMAIL" = "#{old}" ]; then
         GIT_AUTHOR_EMAIL="#{new}";
         GIT_COMMITTER_EMAIL="#{new}";
         git commit-tree "$@";
      else
         git commit-tree "$@";
      fi'`
  end

  # update name of author and committer
  def update_name (old, new)
    `git filter-branch -f --commit-filter '
       if [ "$GIT_AUTHOR_NAME" = "#{old}" ]; then
         GIT_AUTHOR_NAME="#{new}";
         GIT_COMMITTER_NAME="#{new}";
         git commit-tree "$@";
      else
         git commit-tree "$@";
      fi'`
  end
end

ChangeAuthor.new(ARGV).run
